# Worksheet 04

Name:  Xavier Thomas
UID: U72282207

### Topics

- Distance & Similarity

### Distance & Similarity

#### Part 1

a) In the minkowski distance, describe what the parameters p and d are.

p: Norm value
d: Dimension

b) In your own words describe the difference between the Euclidean distance and the Manhattan distance.

Euclidean distance: Uses the Pythagorean theorem to calculate the distance as the straight-line distance between two points.

Manhattan distance: Measures the distance by summing the absolute differences of coordinates along each dimension.

Consider A = (0, 0) and B = (1, 1). When:

- p = 1, d(A, B) = 2
- p = 2, d(A, B) = $\sqrt{2} = 1.41$
- p = 3, d(A, B) = $2^{1/3} = 1.26$
- p = 4, d(A, B) = $2^{1/4} = 1.19$

c) Describe what you think distance would look like when p is very large.

As p become very large, the fraction 1/p --> 0, thereby d(A, B) --> 2^0 = 1. i.e the distance would approach 1

d) Is the minkowski distance still a distance function when p < 1? Expain why / why not.

No, when p < 1 --> 1/p > 1, this would lead to a violation in the triangle inequality and hence is not a distance function.

Consider D(B, A) + D(A, C) = 2
D(B, C) = 2^(1/p)

So D(B, C) > D(B, A) + D(A, C) which violates the traingle inequality

e) when would you use cosine similarity over the euclidan distance?

When direction matters over direction

f) what does the jaccard distance account for that the manhattan distance doesn't?

The Jaccard distance accounts for the presence or absence of elements in sets, while the Manhattan distance considers both magnitude and direction of differences in vectors.

#### Part 2

Consider the following two sentences:

In [1]:
s1 = "hello my name is Alice"  
s2 = "hello my name is Bob"

using the union of words from both sentences, we can represent each sentence as a vector. Each element of the vector represents the presence or absence of the word at that index.

In this example, the union of words is ("hello", "my", "name", "is", "Alice", "Bob") so we can represent the above sentences as such:

In [2]:
v1 = [1,    1, 1,   1, 1,    0]
#     hello my name is Alice
v2 = [1,    1, 1,   1, 0, 1]
#     hello my name is    Bob

Programmatically, we can do the following:

In [3]:
corpus = [s1, s2]
all_words = list(set([item for x in corpus for item in x.split()]))
print(all_words)
v1 = [1 if x in s1 else 0 for x in all_words]
print(v1)

['name', 'Alice', 'my', 'hello', 'Bob', 'is']
[1, 1, 1, 1, 0, 1]


Let's add a new sentence to our corpus:

In [4]:
s3 = "hi my name is Claude"
corpus.append(s3)

a) What is the new union of words used to represent s1, s2, and s3?

In [5]:
all_words = list(set([item for x in corpus for item in x.split()]))
print(all_words)

['name', 'hi', 'Alice', 'my', 'Claude', 'hello', 'Bob', 'is']


b) Represent s1, s2, and s3 as vectors as above, using this new set of words.

In [6]:
v1 = [1 if x in s1 else 0 for x in all_words]
v2 = [1 if x in s2 else 0 for x in all_words]
v3 = [1 if x in s3 else 0 for x in all_words]
print(v1, v2, v3)

[1, 0, 1, 1, 0, 1, 0, 1] [1, 0, 0, 1, 0, 1, 1, 1] [1, 1, 0, 1, 1, 0, 0, 1]


c) Write a function that computes the manhattan distance between two vectors. Which pair of vectors are the most similar under that distance function?

In [7]:
import numpy as np
def manhattan_dist(vector1, vector2):
    vector1 = np.asarray(vector1)
    vector2 = np.asarray(vector2)
    return np.sum(np.abs(vector1 - vector2))

d12 = manhattan_dist(v1, v2)
d13 = manhattan_dist(v1, v3)
d23 = manhattan_dist(v2, v3)

print(d12, d13, d23)

print(f'S1 and S2 are the most similar, with the least distance of {d12}')

2 4 4
S1 and S2 are the most similar, with the least distance of 2


d) Create a matrix of all these vectors (row major) and add the following sentences in vector form:

- "hi Alice"
- "hello Claude"
- "Bob my name is Claude"
- "hi Claude my name is Alice"
- "hello Bob"

In [8]:
s1 = "hi Alice"
s2 = "hello Claude"
s3 = "Bob my name is Claude"
s4 = "hi Claude my name is Alice"
s5 = "hello Bob"
corpus = [s1, s2, s3, s4, s5]
all_words = list(set([item for x in corpus for item in x.split()]))

v1 = [1 if x in s1 else 0 for x in all_words]
v2 = [1 if x in s2 else 0 for x in all_words]
v3 = [1 if x in s3 else 0 for x in all_words]
v4 = [1 if x in s4 else 0 for x in all_words]
v5 = [1 if x in s5 else 0 for x in all_words]

matrix = np.asarray([v1, v2, v3, v4, v5])
print(matrix)

[[0 1 1 0 0 0 0 0]
 [0 0 0 0 1 1 0 0]
 [1 0 0 1 1 0 1 1]
 [1 1 1 1 1 0 0 1]
 [0 0 0 0 0 1 1 0]]


e) How many rows and columns does this matrix have?

In [9]:
print(f"num rows: {matrix.shape[0]}")
print(f"num columns: {matrix.shape[1]}")

num rows: 5
num columns: 8


f) When using the Manhattan distance, which two sentences are the most similar?

In [10]:
distances = []
for i in range(len(matrix)):
    for j in range(i + 1, len(matrix)):
        distance = np.sum(np.abs(np.array(matrix[i]) - np.array(matrix[j])))
        distances.append((i, j, distance))

most_similar_pair = min(distances, key=lambda x: x[2])
sentence1_index, sentence2_index, min_distance = most_similar_pair

print("Most similar sentences:", corpus[sentence1_index], "and", corpus[sentence2_index])
print("Manhattan distance between them:", min_distance)

Most similar sentences: hello Claude and hello Bob
Manhattan distance between them: 2
